### ISSUE TITLE
Merge Makefiles

### ISSUE THREAD

**Issue by dotted** [dkfans/ADiKtEd#3]
> You have made changes to `libadikted/Makefile` can you make sure it's in sync with `libadikted/Makefile.win` as that file has been updated to let it compile with GCC 9.2.0. Better yet, merge the files so we don't have an issue of those go out of sync in the future.

I'll action this ASAP dotted, and will aim to merge the files. What environment did you use to build libadikted? Your Makefile.win did not work with MSYS2.

For reference, Sim now has both `libadikted/Makefile` and `mapslang/Makefile` in a state where one can build map.exe (and libslang.dll/adikted.dll) using MSYS2 (MinGW32).

_Originally posted by @eddebaby in https://github.com/dkfans/ADiKtEd/pull/2#issuecomment-700298937_

**Comment by dotted** [comment]
So I just updated my MSYS install and tried to compile it. The issue I ran into is the `-Werror` parameter preventing compilation, I removed that (see patch) and it seems to compile just fine on my end.

I'm also using the `MSYS2 MinGW 32-bit` shortcut to start my environment and not `MSYS2 MSYS`, that seemed to compilation problems probably due to missing `-m32` compiler flag, and linking completely failed, though not sure why.

[patch.diff.gz](https://github.com/dkfans/ADiKtEd/files/5298640/patch.diff.gz)

**Comment by eddebaby** [comment]
We were using `mingw32-make` rather than `make`, which is from the `mingw-w64-i686-make` package to work with Sim's Makefile's. But I'm aiming to get this as widely compatible as possible.

I have tested `make` with libadikted and I get the same results as you (Need to remove `-Werror` to get it to compile) with `Makefile.win`.

I'll work on libadikted's `Makefile`/`Makefile.win` first, and then make a PR. Once we agree on that, I'll do the same work to mapslang and update the PR.

**Comment by SimLV** [comment]
I  think we should have single Makefile and I would be glad if you port map editor to linux because I am unable to run it using wine.

**Comment by eddebaby** [comment]
Yes that is the plan Sim. :)

**Comment by dotted** [comment]
With Linux compatibility we could setup a CI using the server hosting the Keeper Klan forum and KeeperFX website, so +1 on the Linux support from me.
